# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6bccd7b1c208e935ebf720a1fd4990d5"
name = "xeno-discount-app"
application_url = "https://alert-il-matt-bs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extensibility-dev-kislay.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://alert-il-matt-bs.trycloudflare.com/auth/callback",
  "https://alert-il-matt-bs.trycloudflare.com/auth/shopify/callback",
  "https://alert-il-matt-bs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
